Style/Documentation:
  Enabled: False
AllCops:
  Exclude:
    - bin/*
    - node_modules/*
    - vendor/bundle/**/*
    - config/*
    - config/*/*
    - db/*
    - db/*/*

Metrics/BlockLength:
  Enabled: False
