require:
  - rubocop-rails
  - rubocop-rspec
Style/Documentation:
  Enabled: False
AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - node_modules/*
    - vendor/bundle/**/*
    - config/*
    - config/*/*
    - db/*
    - db/*/*

Metrics/BlockLength:
  Enabled: False
RSpec/NestedGroups:
  Max: 10
RSpec/MultipleMemoizedHelpers:
  Max: 10
Rails/LexicallyScopedActionFilter:
  Exclude:
    - app/controllers/users/*

